#ifndef COMMANDS_H
#define COMMANDS_H

typedef enum {
    CMD_NONE = 0x00,
    CMD_SET_ADCS_MODE = 0x01,
    CMD_SET_ADCS_TARGET = 0x02,
    CMD_GET_BASE_SENSOR_DATA = 0x03,
    CMD_GET_SAT_XCVR_DATA = 0x04,
    CMD_GET_SAT_ADCS_DATA = 0x05,
    CMD_RESP_SAT_XCVR_DATA = 0x10,
    CMD_RESP_BASE_SENSOR_DATA = 0x11,
    CMD_RESP_SAT_ADCS_DATA = 0x12,
    CMD_RESP_ACK = 0x20,
    CMD_RESP_NACK = 0x21
} CMD_e;

#endif